### PR TITLE
Fix directions for setting sonLibRootDir

### PR DESCRIPTION
**Pull request by nathanweeks**

### CODE REVIEW

**Comment by diekhans** [comment]
actually, these should be set by creating a file include.local.mk. This is optional and not in git, so there are no conflicts on update.

I can see I only casually mentioned in the README.md, but it is a slightly better described in the [cactus readme](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/README.md)

Would you mind describing this?

Also, please just delete README.pdf in the PR.

**Comment by nathanweeks** [comment]
> actually, these should be set by creating a file include.local.mk. This is optional and not in git, so there are no conflicts on update.

That sounds like a better solution. And to be honest, I build HAL by setting the sonLibRootDir make macro, e.g.: 
```
make sonLibRootDir=/path/to/sonLib
```
which doesn't require the creation or modification of files. Do you have a preference of which approach to document?

> Also, please just delete README.pdf in the PR.

Will do!

**Comment by diekhans** [comment]
I like using include.local.mk because you don't have to remember
to set it each time.

OK to mention both too.

Thank you for the change!

**Comment by nathanweeks** [comment]
At the risk of scope-creeping this PR: is git://github.com/ComparativeGenomicsToolkit/sonLib.git now the preferred repo that should be used for hal?

**Comment by diekhans** [comment]
Yes, it is

  git://github.com/ComparativeGenomicsToolkit/sonLib.git

sorry if I didn't correctly update the doc.  I owe you one!

**Comment by diekhans** [comment]
I resolved a conflict locally and merged the change from the command line.
Thanks for the contributions; apologies that I was delayed in merging it.

**Pull request merged**
